export const GET_DIALOG_LIST = 'GET_DIALOG_LIST';
export const GET_DIALOG_MESSAGES = 'GET_DIALOG_MESSAGES';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
